### ISSUE TITLE
Marti que significa aixo

### ISSUE THREAD

**Issue by wextia** [wextia/local-search#1]
[Que estas fent en aquesta linea](https://github.com/wextia/local-search/blob/master/src/ia/StatePrac.java#L85)

**Comment by martiitram** [comment]
mirar si hi ha un cicle o acabo a una central

**Comment by martiitram** [comment]
El que està fent és: si no estic a l'origen o a una central ves al node que està conectat

**Comment by wextia** [comment]
Ok gracies!
